version = 0.1
[default.deploy.parameters]
stack_name = "cognito-lambdas"
resolve_s3 = true
s3_prefix = "cognito-lambdas"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "UserPoolArn=\"arn:aws:cognito-idp:eu-central-1:448953121568:userpool/eu-central-1_ifdSGatOd\" UserPoolId=\"\" ClientId=\"\""
image_repositories = []
